//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeTaskDbEntities : DbContext
    {
        public EmployeeTaskDbEntities()
            : base("name=EmployeeTaskDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbldesignation> tbldesignations { get; set; }
        public virtual DbSet<tblemployee_experiance_details> tblemployee_experiance_details { get; set; }
        public virtual DbSet<tblemployee_experiance_projects> tblemployee_experiance_projects { get; set; }
        public virtual DbSet<tblemployee> tblemployees { get; set; }
        public virtual DbSet<tblproject_responsibility> tblproject_responsibility { get; set; }
    }
}
