//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblemployee()
        {
            this.tblemployee_experiance_details = new HashSet<tblemployee_experiance_details>();
        }
    
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Email_Address { get; set; }
        public string mobile_number { get; set; }
        public string Employee_Code { get; set; }
        public string password { get; set; }
        public string Profile_Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblemployee_experiance_details> tblemployee_experiance_details { get; set; }
    }
}
