//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee_experiance_projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblemployee_experiance_projects()
        {
            this.tblproject_responsibility = new HashSet<tblproject_responsibility>();
        }
    
        public int Project_Id { get; set; }
        public Nullable<int> Experiance_Id { get; set; }
        public string Project_Name { get; set; }
        public string From_Duration { get; set; }
        public string To_Duration { get; set; }
        public Nullable<int> Team_Size { get; set; }
        public string Role { get; set; }
        public string Project_Description { get; set; }
    
        public virtual tblemployee_experiance_details tblemployee_experiance_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblproject_responsibility> tblproject_responsibility { get; set; }
    }
}
